server:
  port: 8010

spring:
  application:
    name: event-consumer-service

  config:
    #    import: optional:configserver:${CONFIG_SERVER_URL:http://192.168.192.2:30088} # VPN
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-service:8888} # VPN

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

rabbitmq:
  exchanges:
    user: user.exchange
    post: post.exchange

  queues:
    user:
      created: user.created.queue
      deleted: user.deleted.queue
    post:
      created: post.created.queue
      deleted: post.deleted.queue

  routing-keys:
    user:
      created: user.created
      deleted: user.deleted
    post:
      created: post.created
      deleted: post.deleted
