apiVersion: v1
kind: Service
metadata:
  name: event-consumer-service
  labels:
    app: event-consumer-service
spec:
  selector:
    app: event-consumer-service
  ports:
    - name: http
      port: 8010
      targetPort: 8010
      nodePort: 30010
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-consumer-service
  template:
    metadata:
      labels:
        app: event-consumer-service
    spec:
      containers:
        - name: dummy
          image: alpine
          command: ["sleep", "3600"]